language: ruby
cache: bundler
rvm:
- 2.2.3
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
addons:
  postgresql: '9.4'
deploy:
  provider: heroku
  api_key:
    secure: kVCOhd6kq8gIkkNIhCYts+no2c0PmfXUE0Poh0AXDCRXTzJ/QjfmzXXTCPGSU+t5yZnuBlQHA7ov72Cb3ug68eLguGmEt1XuBJN3OAz2trJ8XAZGyyTQ7KRWKHmu6tuqYi1N8hLhPddjibOjRdG162Lbe5tPPSkVMU7ODj2wZBjHv55xmNLTckGs5SkSCgOP1fXim0g6v/jjiI4Ui7wTNvmh/kBJRQ+Ap3ToY6b3UuAF6LQwZWg+FLXER7VVShBtvblV8eJ0b+mS2xYfRaiwVZUajuK5n/c/1LWJr7nzKF4HttmijcQ/viDvV6j85Cyp1KA0FLR36zHK3WnN5S/GMNRW5Z5TSCrnrPF+bvhWrqRTo92tpxZ8tqarHZCdElUJ6HECrAA7xEAkpR20XausWFuiFc4SzFsjmk1LeDnCrXP9ss2yo6DCJsKqHUhX06/ITaTF15GyKJSCn/TqSSgPpmvYfDgnWeabAgwSIxR2Js8mtB+ii9xN35noojVj39ZNSwmgQkTl+INej7hYyOSUBdiSUycSTQKINch5DXXeV4xY4s9M85MyIfKIu2N384DqQYdzHOl+AKOJohKeI+/csG8VJ20LlMNWFI/esODuS0196wWEzKMsHSA0H+J/fpjC3xJYR3VhFtc57nOK1lutEnlOEiWtQPmVadO6JnxblbQ=
  app: BloodBank
  on:
    repo: Kiloreux/BloodBank
Kiloreux/BloodBank:
  secure: MsGCeLm4Zw0nt5SPOkr78nFOULeIW9CUwX9YHS2mLvWquR8sSkeLbaRPGjVZB+IMIXicMUQPOaf1mqKUDitCl+wnOsEJ+qWRGeCZ9LhO9B3OrOI0wgMnpUNfBozGddxiwe+PYY5ehw+EXxh8coLBANCao9pHNSkV38XD7+1coOeSquNPitJKaXpU/KZRx+6sdGTnmhgWjZ+aWyd5z7QJFM+Z5NBhrrLid8RnlMqGQJT7symr8CJnTIRNvxnvsmYq6Bzor7ajY1bNZHkNK7P5pfopPXeemUlJLOlnL5lvwOdnH5mULXlNckBy7w39syXm5esrpOlz59elN334i7kPCD6sIK7FH1BUwn7jXkaTV0AOcBC/HMuf1igIL5GU7QBUTc5Ytr6Bo+XgZiL36Yx4pyDAQX41Wa5Dnskt/XpSOcVgOQ/9/oPFYgpAVi1aP2by7c+J9SPCyAslsfG0gQTxiF/jlMcTHaxx7iBiLJ/zolziRmi3tvEZBieP2p15S6svsWkvDJCd7Q8DEiB6Bz8qoVHfFF67j/VucWQsSXH1GTs3UdgJEG71pLiwuXUyDinKkioMeB3YojigXlEI4Emx+vmmsy6F731UPQS1BNr/EqiT5ijQUcbIDmPD26TacpCztM0RXILFMhN60EA3uoYw0WcPj31gkm7Iaa/kv6D1WcQ=
