development: &dev
  adapter: postgresql
  encoding: unicode
  database: bb_development
  pool: 20
  username: kiloreux
  password: kiloreux

test: &test
  <<: *dev
  database: bb_test

production:
  <<: *dev
  database: bb_production

cucumber:
  <<: *test
