# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 456cb80b8b809d45c7607191dacbf32d5ea8fb4daf6a422b75c7f609039c3b73d4ad848cbe58311c3ced59887d810a03805c961adc5005e7d484bbd99ac93310

test:
  secret_key_base: 217c87517a9c49725907d42be241ed6327e49372914fec0c647449b63a5cc522c4bcb8291ab7f0290ae3d1cef59ff0bd9f0bd37a987edd586a965fab840ff80b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
